name: "Inso"
description: "Inso"
inputs:
  opt-string:
    description: "options"
    required: true
    default: "--help"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.opt-string }}
